package com.farmutils.calc;

public enum CalcCropFlag
{
    HAS_PROPAGATION_CHAIN,
    PROTECTS_NEIGHBOURS,
    CANNOT_BE_PROTECTED,
    NON_TRADEABLE_OUTPUT,
    ACTIVE_INTERVENTION_ONLY,
    REPEAT_PICK,
    SPECIAL_PROTECTION_PAYMENT
}
